### ISSUE TITLE
Fix(exit): exit -

### ISSUE THREAD

**Issue by KCarriolo** [Grsaiago/minishell#83]
- Quit the program (our remains in the program)
- Output: "bash: exit: -: numeric argument required"
- Exit_status = 255 (2 at moment)

**Comment by Grsaiago** [comment]
With "-":
- Quits the program (our remains in the program)
- Output: "bash: exit: -: numeric argument required"
- Exit_status = 255 (2 at moment)

With "--2":
- Quits the program.

- Output should be:
"bash: exit: --2: numeric argument required"

- Our exit_status = 2
should be 255
